# Generated by Django 3.2.6 on 2021-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='hobbie')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'hobbie',
                'verbose_name_plural': 'hobbies',
            },
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='intereces')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'intere',
                'verbose_name_plural': 'interes',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('pensamiento', models.TextField(max_length=500)),
                ('telefono', models.TextField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('likein', models.CharField(max_length=50)),
                ('cumpleanos', models.DateTimeField(null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('curriculo', models.FileField(null=True, upload_to='curriculo')),
                ('imagen', models.ImageField(null=True, upload_to='perfil')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfils',
            },
        ),
    ]
