# Generated by Django 3.2.6 on 2021-09-01 20:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen_icono', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'hobbie',
                'verbose_name_plural': 'hobbies',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('pensamiento', models.TextField(max_length=500)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('likein', models.CharField(max_length=50)),
                ('cumpleanos', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('curriculo', models.FileField(null=True, upload_to='curriculo')),
                ('imagen', models.ImageField(null=True, upload_to='perfil')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfils',
            },
        ),
    ]
