# Generated by Django 3.2.6 on 2021-08-30 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='imagen_base',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
